project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"

website:
  title: "US Vehicle Trends"
  image: images/logo.png
  site-url: https://vehicletrends.us
  favicon: images/favicon.ico
  repo-url: https://github.com/vehicletrends/dashboard
  search: true
  back-to-top-navigation: false
  repo-actions: [edit, issue]
  description: 'Something'
  open-graph:
    locale: es_ES
    site-name: https://vehicletrends.us
  google-analytics:
    tracking-id: "G-GL9TW3F8RJ"
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/logo.png"
    card-style: summary
  sidebar:
    style: "docked"
    background: "light"
    logo: images/logo.png
    collapse-level: 1
    search: true
    contents:
    - text: About
      icon: info-circle-fill
      href: about.qmd
    - text: "Daily VMT"
      icon: speedometer2
      href: vmt-daily.qmd
    - text: "VMT by Age"
      icon: graph-up
      href: vmt-age.qmd
    - text: "Depreciation"
      icon: graph-down
      href: depreciation.qmd
    - text: "Percent of Market"
      icon: pie-chart-fill
      href: percent-market.qmd
    - text: "Percent of Dealers"
      icon: shop
      href: percent-dealers.qmd
    - text: "Market Concentration"
      icon: diagram-3-fill
      href: market-concentration.qmd
    - text: "HHI Explained"
      icon: lightbulb-fill
      href: hhi-explained.qmd
    - text: "Registrations"
      icon: map-fill
      href: registrations.qmd
    - text: "Tech Stack"
      icon: gear-fill
      href: tech-stack.qmd
    # - text: "Listings"
    #   icon: list-ul
    #   href: listings.qmd
    # - text: "Dealerships Inventories"
    #   icon: building
    #   href: dealership-inventories.qmd
    # - text: "Nearest Vehicles"
    #   icon: geo-alt
    #   href: nearest-vehicles.qmd

  page-footer:
    center:
      - text: "Â© 2025 John Paul Helveston {{< fa creative-commons-sa >}} <a href='LICENSE.html'><i class='fab fa-creative-commons'></i><i class='fab fa-creative-commons-by'></i><i class='fab fa-creative-commons-sa'></i></a> | <a href='cite.html'>Cite</a> | <a href='https://github.com/vehicletrends/'><i class='fab fa-github'></i></a>"

format:
  html:
    page-layout: full
    theme:
      light: flatly
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: "_includes/header.html"
    toc-location: right
    toc: true
    mainfont: Inter, -apple-system, BlinkMacSystemFont, sans-serif
  
execute:
    echo: false
    message: false