project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"

website:
  title: "US Vehicle Trends"
  image: images/logo.png
  site-url: https://vehicletrends.us
  favicon: images/favicon.ico
  repo-url: https://github.com/vehicletrends
  search: true
  back-to-top-navigation: false
  repo-actions: [edit, issue]
  description: 'Something'
  open-graph:
    locale: es_ES
    site-name: https://github.com/vehicletrends
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/logo.png"
    card-style: summary
  sidebar:
    style: "docked"
    background: "dark" 
    collapse-level: 1
    search: true
    contents:
    - text: About
      icon: question-square-fill
      href: about.qmd
    - text: "Daily VMT"
      icon: clock-fill
      href: daily-vmt.qmd
    - text: "Annual VMT"
      icon: calendar-range
      href: annual-vmt.qmd
    - text: "Depreciation"
      icon: graph-down
      href: depreciation.qmd
    - text: "Market Concentration"
      icon: person-lines-fill
      href: market-concentration.qmd
    - text: "Listings"
      icon: list-ul
      href: listings.qmd
    - text: "Dealerships Inventories"
      icon: building
      href: dealership-inventories.qmd
    - text: "Nearest Vehicles"
      icon: geo-alt
      href: nearest-vehicles.qmd
    - text: "Understanding HHI"
      icon: geo-alt
      href: hhi-explained.qmd


  page-footer:
    center:
      - text: "Â© 2025 John Paul Helveston {{< fa creative-commons-sa >}} <a href='LICENSE.html'><i class='fab fa-creative-commons'></i><i class='fab fa-creative-commons-by'></i><i class='fab fa-creative-commons-sa'></i></a> | <a href='https://github.com/vehicletrends/'><i class='fab fa-github'></i></a>"

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    # This is to include fontawesome icons
    include-in-header: "_includes/header.html"
    toc-location: right
    toc: true
  
execute:
    echo: false
    message: false